- name: install mariadb
  ansible.builtin.apt: name={{ item }} state=present install_recommends=yes update_cache=yes #cache_valid_time=3600
  with_items:
    - mariadb-server
    - mariadb-client

- name: start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: create app db
  community.mysql.mysql_db: name={{ db_name }} state=present login_unix_socket='/var/run/mysqld/mysqld.sock'

- name: create db user
  community.mysql.mysql_user: 
    name: "{{db_user}}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: '/var/run/mysqld/mysqld.sock'